import { createSlice, createEntityAdapter } from '@reduxjs/toolkit';

// Create an entity adapter for blogs
const blogsAdapter = createEntityAdapter();

// Initial state with the entity adapter
const initialState = blogsAdapter.getInitialState({
    tags: [],
    search: '',
    page: 1,
    pageSize: 3,
    tagCount: {},
});

const blogsStateSlice = createSlice({
    name: 'blogs',
    initialState,
    reducers: {
        setAllBlogs(state, action) {
            // Use the adapter's upsertMany method to update the state
            blogsAdapter.upsertMany(state, action.payload);
        },

        setTags(state, action) {
            state.tags = action.payload;
        },

        setSearch(state, action) {
            state.search = action.payload;
        },

        setPage(state, action) {
            state.page = action.payload;
        },

        setTagCount(state, action) {
            state.tagCount = action.payload;
        },
    },
});

export const { setTags, setSearch, setPage, setTagCount, setAllBlogs } = blogsStateSlice.actions;
export default blogsStateSlice.reducer;

// Export selectors generated by the adapter
export const {
    selectAll: selectAllBlogs,
    selectById: selectBlogById,
} = blogsAdapter.getSelectors(state => state.blogs);